nothing:
	python disassemble.py nothing > nothing.bytecode

throws:
	python disassemble.py throws > throws.bytecode

try:
	python disassemble.py try > try.bytecode

many:
	python disassemble.py many > many.bytecode

nothing3:
	python3 disassemble.py nothing > nothing3.bytecode

throws3:
	python3 disassemble.py throws > throws3.bytecode

try3:
	python3 disassemble.py try > try3.bytecode

many3:
	python3 disassemble.py many > many3.bytecode

all3: nothing3 throws3 try3 many3

all: nothing throws try many
